#!/usr/bin/env bash

function install_virtualbox() {
  echo -e "\n###############################################\n" | sudo tee -a /etc/apt/sources.list > /dev/null
  echo "# Virtualbox" | sudo tee -a /etc/apt/sources.list > /dev/null

  echo "deb [arch=amd64 signed-by=/usr/share/keyrings/oracle-virtualbox-2016.gpg] https://download.virtualbox.org/virtualbox/debian bookworm contrib" | sudo tee -a /etc/apt/sources.list > /dev/null

  wget -O- https://www.virtualbox.org/download/oracle_vbox_2016.asc | sudo gpg --yes --output /usr/share/keyrings/oracle-virtualbox-2016.gpg --dearmor

  sudo apt-get update
  sudo apt-get install -y virtualbox-7.1

}

function install_snap() {
  sudo apt-get install snapd
  sudo snap install snapd
}

function install_bitwarden() {
  install_snap
  sudo snap install bitwarden
}

function install_visual_studio_code() {
  sudo apt-get install wget gpg pkexec
  wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
  sudo install -D -o root -g root -m 644 packages.microsoft.gpg /etc/apt/keyrings/packages.microsoft.gpg
  echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" | sudo tee /etc/apt/sources.list.d/vscode.list > /dev/null
  rm -f packages.microsoft.gpg

  sudp apt install apt-transport-https
  sudo apt update
  sudo apt install code

}

function install_google_chrome() {
  curl -OL https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

  sudo apt-get install ./google-chrome-stable_current_amd64.deb

  rm google-chrome-stable_current_amd64.deb
}

function install_gnome() {
  sudo apt-get install --no-install-recommends gnome-core
  systemctl reboot
  return 0
}

function install_all_tools() {
  ./install_gnome_themes
  ./install_gnome_icons
  install_google_chrome
  install_visual_studio_code
  install_bitwarden
  install_virtualbox
  return 0
}

function main() {
  local tools=(${@})
  if [[ " ${tools[@]} " =~ " all " ]]; then
    if ! install_all_tools ; then return 1; fi
    return 0;
  fi

  for tool in ${tools[@]}; do
    case "${tool}" in
      "gnome")
        if ! install_gnome ; then return 1; fi
      ;;
      "gnome-themes")
        if ! ./install_gnome_themes ; then return 1; fi
      ;;
      "gnome-icons")
        if ! ./install_gnome_icons ; then return 1; fi
      ;;
      "google-chrome")
        if ! install_google_chrome ; then return 1; fi
      ;;
      "vscode")
        if ! install_visual_studio_code ; then return 1; fi
      ;;
      "bitwarden")
        if ! install_bitwarden ; then return 1; fi
      ;;
      "virtualbox")
        if ! install_virtualbox ; then return 1; fi
      ;;
      *)
        echo "'${tool}' is not a tool for being installed" >&2 && continue
      ;;
    esac
  done
}

main "${@}"