#!/usr/bin/env bash

function install_sweet_folders_icons() {
  git clone https://github.com/EliverLara/Sweet-folders.git

  mv Sweet-folders/Sweet-* ~/.local/share/icons

  rm -rf Sweet-folders
}

function install_candy_icons() {
  curl -OL https://github.com/EliverLara/candy-icons/archive/refs/heads/master.zip

  unzip master.zip -d ~/.local/share/icons

  mv ~/.local/share/icons/candy-icons-master ~/.local/share/icons/candy-icons

  rm master.zip
}

function install_dracula_icons() {
  curl -OL https://github.com/dracula/gtk/files/5214870/Dracula.zip

  unzip Dracula.zip -d ~/.local/share/icons

  rm Dracula.zip
}

function install_dependencies() {
  sudo apt-get install \
  curl \
  unzip \
  git

  return 0
}

function main() {
  install_dependencies || exit 1

  # Create icons directory
  mkdir -p ~/.local/share/icons

  install_dracula_icons || exit 1
  install_candy_icons || exit 1
  install_sweet_folders_icons || exit 1

  exit 0
}

main